### ISSUE TITLE
Camera is broken

### ISSUE THREAD

**Issue by K900** [skirata/tf101-jelly#1]
Subj.

**Comment by K900** [comment]
Relevant: https://review.teameos.org/#/c/775/1/etc/nvcamera.conf

**Comment by skirata** [comment]
Did you fix it ?

**Comment by K900** [comment]
Nope, had zero time today.
19.07.2012 18:12 пользователь "skirata" <
reply@reply.github.com>
написал:

**Comment by K900** [comment]
Closed, needs #2
