### ISSUE TITLE
adb shell

### ISSUE THREAD

**Issue by Southern** [skirata/tf101-jelly#3]
Still not working for me. `/system/bin/sh` has been removed from the ROM?

**Comment by skirata** [comment]
/system/bin/sh is there (symlink)

but somehow, it does not work currently. 

Maybe I will fix this the next days. K900 reported adb shell working though.

**Comment by Southern** [comment]
Ah. I'm not currently on the ROM at the moment, but I didn't see a symlink file from TWRP when I went browsing for it.

**Comment by K900** [comment]
Use jellybean adb, the one from build. out/host/linux-x86/bin/adb IIRC.

**Comment by Southern** [comment]
Using build 2 works. I posted this from build 1.
